/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BacklogImport } from './routes/backlog'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIdImport } from './routes/projects/$id'
import { Route as ProjectsIdBacklogImport } from './routes/projects/$id/backlog'

// Create/Update Routes

const BacklogRoute = BacklogImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIdRoute = ProjectsIdImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIdBacklogRoute = ProjectsIdBacklogImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => ProjectsIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogImport
      parentRoute: typeof rootRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdImport
      parentRoute: typeof rootRoute
    }
    '/projects/$id/backlog': {
      id: '/projects/$id/backlog'
      path: '/backlog'
      fullPath: '/projects/$id/backlog'
      preLoaderRoute: typeof ProjectsIdBacklogImport
      parentRoute: typeof ProjectsIdImport
    }
  }
}

// Create and export the route tree

interface ProjectsIdRouteChildren {
  ProjectsIdBacklogRoute: typeof ProjectsIdBacklogRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdBacklogRoute: ProjectsIdBacklogRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$id/backlog': typeof ProjectsIdBacklogRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$id/backlog': typeof ProjectsIdBacklogRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$id/backlog': typeof ProjectsIdBacklogRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backlog'
    | '/projects/$id'
    | '/projects/$id/backlog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/backlog' | '/projects/$id' | '/projects/$id/backlog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/backlog'
    | '/projects/$id'
    | '/projects/$id/backlog'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BacklogRoute: typeof BacklogRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BacklogRoute: BacklogRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/backlog",
        "/projects/$id"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/backlog": {
      "filePath": "backlog.jsx"
    },
    "/projects/$id": {
      "filePath": "projects/$id.jsx",
      "children": [
        "/projects/$id/backlog"
      ]
    },
    "/projects/$id/backlog": {
      "filePath": "projects/$id/backlog.jsx",
      "parent": "/projects/$id"
    }
  }
}
ROUTE_MANIFEST_END */
