/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIdIndexImport } from './routes/projects/$id/index'
import { Route as ProjectsIdBacklogImport } from './routes/projects/$id/backlog'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIdIndexRoute = ProjectsIdIndexImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIdBacklogRoute = ProjectsIdBacklogImport.update({
  id: '/projects/$id/backlog',
  path: '/projects/$id/backlog',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/projects/$id/backlog': {
      id: '/projects/$id/backlog'
      path: '/projects/$id/backlog'
      fullPath: '/projects/$id/backlog'
      preLoaderRoute: typeof ProjectsIdBacklogImport
      parentRoute: typeof rootRoute
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/$id/backlog': typeof ProjectsIdBacklogRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/$id/backlog': typeof ProjectsIdBacklogRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/$id/backlog': typeof ProjectsIdBacklogRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/projects/$id/backlog' | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/projects/$id/backlog' | '/projects/$id'
  id: '__root__' | '/' | '/about' | '/projects/$id/backlog' | '/projects/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectsIdBacklogRoute: typeof ProjectsIdBacklogRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectsIdBacklogRoute: ProjectsIdBacklogRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/projects/$id/backlog",
        "/projects/$id/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/projects/$id/backlog": {
      "filePath": "projects/$id/backlog.jsx"
    },
    "/projects/$id/": {
      "filePath": "projects/$id/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
